[package]
name = "system_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.32.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde_json = "1.0.133"
serde = "1.0.215"
clap = { version = "4.5.23", features = ["derive"] }
kafka = "0.10"