[package]
name = "system_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.32.1"
clap = { version = "4.5.23", features = ["derive"] }
kafka = "0.10"
image = "0.25.5"
ndarray = "0.16.1"